-- ============================================================
-- DATACHAT BI PLATFORM - DATABASE SCHEMA INITIALIZATION
-- ============================================================
-- Reference/documentation file for the database schema.
-- The schema poc_metadata and its 3 tables already exist in the
-- database datachat_db. This file documents the full SQL used
-- to create them, and the public.orders table definition.
--
-- Usage (if recreating from scratch):
--   psql -U postgres -d datachat_db -f database/init_schema.sql
-- ============================================================

-- Ensure UUID extension is available
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- SCHEMA: poc_metadata (Metadata POC)
-- ============================================================

CREATE SCHEMA IF NOT EXISTS poc_metadata AUTHORIZATION datachat_user;
GRANT ALL ON SCHEMA poc_metadata TO datachat_user;

-- ============================================================
-- TABLE: poc_metadata.saved_charts
-- Stores saved charts with parametric metadata for post-creation
-- parameter modification (e.g., change time granularity).
-- ============================================================

CREATE TABLE IF NOT EXISTS poc_metadata.saved_charts (
    chart_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id VARCHAR(100),                          -- Future multi-user (nullable for POC)
    title VARCHAR(200) NOT NULL,
    description TEXT,
    sql_template TEXT NOT NULL,                     -- SQL with placeholder {param_name}
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,  -- Modifiable parameter schema
    plotly_config JSONB NOT NULL,                   -- Complete Plotly configuration
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_saved_charts_created
    ON poc_metadata.saved_charts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_saved_charts_user
    ON poc_metadata.saved_charts(user_id)
    WHERE user_id IS NOT NULL;

COMMENT ON TABLE poc_metadata.saved_charts
    IS 'Saved charts with parametric metadata for post-creation modification';
COMMENT ON COLUMN poc_metadata.saved_charts.sql_template
    IS 'SQL with placeholders like {time_granularity} for parameterization';
COMMENT ON COLUMN poc_metadata.saved_charts.parameters
    IS 'JSONB schema: {param_name: {type, current, options, label}}';

-- ============================================================
-- TABLE: poc_metadata.query_history
-- Stores NL query history for analytics and debugging.
-- ============================================================

CREATE TABLE IF NOT EXISTS poc_metadata.query_history (
    query_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id VARCHAR(100) NOT NULL,
    nl_query TEXT NOT NULL,                -- Natural language question
    sql_generated TEXT,                    -- SQL generated by Vanna/LLM
    llm_provider VARCHAR(20),             -- 'claude' | 'azure'
    success BOOLEAN NOT NULL DEFAULT false,
    error_message TEXT,
    execution_time_ms INTEGER,            -- Total latency in ms
    result_rows INTEGER,                  -- Number of result rows
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_query_history_session
    ON poc_metadata.query_history(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_history_success
    ON poc_metadata.query_history(success, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_history_created
    ON poc_metadata.query_history(created_at DESC);

COMMENT ON TABLE poc_metadata.query_history
    IS 'NL-to-SQL query history for analytics and debugging';

-- ============================================================
-- TABLE: poc_metadata.vanna_training_data
-- Backup of Vanna 2.0 training pairs (embeddings live in ChromaDB).
-- ============================================================

CREATE TABLE IF NOT EXISTS poc_metadata.vanna_training_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nl_question TEXT NOT NULL,             -- Natural language example question
    sql_query TEXT NOT NULL,               -- Corresponding correct SQL
    ddl_context TEXT,                      -- Optional DDL schema context
    approved BOOLEAN NOT NULL DEFAULT true, -- User-approved for training
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vanna_training_approved
    ON poc_metadata.vanna_training_data(approved, created_at DESC);

COMMENT ON TABLE poc_metadata.vanna_training_data
    IS 'Vanna 2.0 training data backup (embeddings stored in ChromaDB)';

-- ============================================================
-- GRANTS for poc_metadata schema
-- ============================================================

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA poc_metadata TO datachat_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA poc_metadata TO datachat_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA poc_metadata
    GRANT ALL ON TABLES TO datachat_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA poc_metadata
    GRANT ALL ON SEQUENCES TO datachat_user;

-- ============================================================
-- TABLE: public.orders (Kaggle Superstore Sales dataset)
-- Single-table denormalized schema for POC simplicity.
-- Populated by scripts/import_kaggle_dataset.py
-- ============================================================

CREATE TABLE IF NOT EXISTS public.orders (
    row_id SERIAL PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(200),
    sales DECIMAL(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    discount DECIMAL(5,2),
    profit DECIMAL(10,2)
);

-- Performance indexes on key query columns
CREATE INDEX IF NOT EXISTS idx_orders_order_date ON public.orders(order_date);
CREATE INDEX IF NOT EXISTS idx_orders_category ON public.orders(category);
CREATE INDEX IF NOT EXISTS idx_orders_sub_category ON public.orders(sub_category);
CREATE INDEX IF NOT EXISTS idx_orders_region ON public.orders(region);
CREATE INDEX IF NOT EXISTS idx_orders_state ON public.orders(state);
CREATE INDEX IF NOT EXISTS idx_orders_segment ON public.orders(segment);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON public.orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_product_id ON public.orders(product_id);

COMMENT ON TABLE public.orders
    IS 'Kaggle Superstore Sales dataset - business data for POC demo (~9994 rows)';

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================
-- Run these after initialization to verify:
--
-- SELECT COUNT(*) FROM information_schema.tables
--   WHERE table_schema = 'poc_metadata';
-- -- Expected: 3
--
-- SELECT COUNT(*) FROM public.orders;
-- -- Expected: ~9994 (after running import_kaggle_dataset.py)
-- ============================================================
